run:
  timeout: 5m
  skip-dirs:
    - testdata
  modules-download-mode: readonly

output:
  format: tab
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Additional linters
    - contextcheck
    - goerr113
    - gofumpt
    - misspell
    - noctx
    - unconvert
    - unparam

issues:
  max-issues-per-linter: 0
  max-same-issues: 20
