# Triggers when a new release is published. Upon publication of the new release, this will tag the
# repository with the shortened major semantic version pointing at the highest semantic version
# within that major version. For example, v1.2.2 and v1 point to the same ref xyz, a new tag is
# introduced v1.2.3 which points to ref abc, this action will move the v1 tag to point to abc
# rather than xyz. This enables consumers of an action to take a "floating" major semantic version
# dependency, like my-action@v1.

name: Move major version
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: "Tag name that the major tag will point to"
        required: true

permissions:
  contents: write

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    runs-on: ubuntu-latest
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        uses: actions/publish-action@v0.1.0
        with:
          source-tag: ${{ env.TAG_NAME }}
